In [19]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pandas.errors import EmptyDataError

In [2]:
climateVariables = [
'PAR_interior_(µmol_m_-2_s_-1)',
'Humedad_Relativa_interior_Alta_(%)',
'Humedad_Relativa_interior_Baja_(%)',
'Humedad_Relativa_interior_Centro_(%)',
'DPV_(kPa)',
'CO2_(ppm)',
'Radiación_Solar_Global_Interior_(W_m_-2)',
'Temperatura_Interior_Alta_(ºC)',
'Temperatura_Interior_Baja_(ºC)',
'Temperatura_Interior_Centro_(ºC)',
'Velocidad_viento_Interior_(m_s)',]

In [ ]:
devicesVariables = [
'Recirculador',
'Calefactores',
'Fog',
'Pantalla_de_sombreo_cenital',
'Pantalla_de_sombreo_lateral_sur',
'Recirculador_centro',
'Ventana_cenital_este',
'Ventana_cenital_oeste',
'Ventana_lateral_norte',
'Ventana_lateral_oeste',
'Ventana_lateral_sur',
#'Luz_artificial_centro-este',
#'Luz_artificial_centro-oeste',
#'Luz_artificial_nor-este',
#'Luz_artificial_nor-oeste',
#'Luz_artificial_sur-este',
#'Luz_artificial_sur-oeste'
]

In [10]:
def readClimaticVariableData(path):
    df = pd.read_csv(path)
    df['_time'] = pd.to_datetime(df['_time'], format='mixed').dt.tz_localize(None).dt.strftime('%Y-%m-%d %H:%M:%S')
    df['_time'] = pd.to_datetime(df['_time'])
    df = df.set_index('_time').resample('min').mean().reset_index()
    return df

In [13]:
temp_centro = readClimaticVariableData('climate devices experiments data/Temperatura_Interior_Centro_(ºC)_0.csv')
temp_centro

                   _time     _value
0    2026-08-03 00:00:00  26.825000
1    2026-08-03 00:01:00  26.813333
2    2026-08-03 00:02:00  26.787500
3    2026-08-03 00:03:00  26.777500
4    2026-08-03 00:04:00  26.760000
...                  ...        ...
6320 2026-08-07 09:20:00  42.680000
6321 2026-08-07 09:21:00  42.755000
6322 2026-08-07 09:22:00  42.830000
6323 2026-08-07 09:23:00  42.922500
6324 2026-08-07 09:24:00  43.015000

[6325 rows x 2 columns]

In [27]:
humedad_centro = readClimaticVariableData('climate devices experiments data/Humedad_Relativa_interior_Centro_(%)_0.csv')
humedad_centro

                   _time     _value
0    2026-08-03 00:00:00  80.942500
1    2026-08-03 00:01:00  81.010000
2    2026-08-03 00:02:00  81.087500
3    2026-08-03 00:03:00  81.192500
4    2026-08-03 00:04:00  81.254000
...                  ...        ...
6320 2026-08-07 09:20:00  35.085000
6321 2026-08-07 09:21:00  34.565000
6322 2026-08-07 09:22:00  34.323333
6323 2026-08-07 09:23:00  34.135000
6324 2026-08-07 09:24:00  33.770000

[6325 rows x 2 columns]

In [28]:
for device in devicesVariables:
    print(f'Plotting {device} data...')
    try:
        device_data = pd.read_csv(f'climate devices experiments data/{device}_0.csv')
    except EmptyDataError as e:
      print(f"No data for device {device}: {e}")
      continue

    device_data['_time'] = pd.to_datetime(device_data['_time'], format='mixed', utc=True)
    # remove the timezone information from the _time column
    device_data['_time'] = device_data['_time'].dt.tz_localize(None)
    device_data['_time'] = device_data['_time'].dt.strftime('%Y-%m-%d %H:%M:%S')
    device_data['_time'] = pd.to_datetime(device_data['_time'])
    device_data['_value'] = device_data['_value'].clip(lower=0)  # set negative values to 0

    if device_data['_value'].max() == 1:
        device_data['_value'] = device_data['_value'] * 100  # convert to percentage

    # drop duplicated rows based on the _time column
    device_data = device_data.drop_duplicates(subset=['_time'])

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=device_data['_time'], y=device_data['_value'], mode='lines', name=device))
    
    fig.add_trace(go.Scatter(x=temp_centro['_time'], y=temp_centro['_value'], mode='lines', name='Temp Centro'))
    fig.add_trace(go.Scatter(x=humedad_centro['_time'], y=humedad_centro['_value'], mode='lines', name='Humedad Centro'))
    fig.show()

Plotting Recirculador data...

Plotting Calefactores data...

Plotting Fog data...

Plotting Pantalla_de_sombreo_cenital data...

Plotting Pantalla_de_sombreo_lateral_sur data...
No data for device Pantalla_de_sombreo_lateral_sur: No columns to parse from file
Plotting Recirculador_centro data...

Plotting Ventana_cenital_este data...

Plotting Ventana_cenital_oeste data...

Plotting Ventana_lateral_norte data...

Plotting Ventana_lateral_oeste data...

Plotting Ventana_lateral_sur data...

Plotting Luz_artificial_centro-este data...
No data for device Luz_artificial_centro-este: No columns to parse from file
Plotting Luz_artificial_centro-oeste data...
No data for device Luz_artificial_centro-oeste: No columns to parse from file
Plotting Luz_artificial_nor-este data...
No data for device Luz_artificial_nor-este: No columns to parse from file
Plotting Luz_artificial_nor-oeste data...
No data for device Luz_artificial_nor-oeste: No columns to parse from file
Plotting Luz_artificial_sur-este data...
No data for device Luz_artificial_sur-este: No columns to parse from file
Plotting Luz_artificial_sur-oeste data...
No data for device Luz_artificial_sur-oeste: No columns to parse from file