In [38]:
import pandas as pd
import requests
from io import StringIO
import openmeteo_requests
import requests_cache
from retry_requests import retry
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pandas.errors import EmptyDataError

# Download inside data

In [29]:
inside_devices_name = [
# climatic variables
'HR_Alta',
'HR_Baja',
'HR_Centro',
'PAR',
'Presión_Barométrica_Alta',
'Presión_Barométrica_Baja',
'Presión_Barométrica_Centro',
'Presión_Vapor_Alta',
'Presión_Vapor_Baja',
'Radiación_Solar_Global',
'Temperatura_Alta',
'Temperatura_Baja',
'Temperatura_Centro',
'Velocidad_viento',

# climatic control systems variables
'Fog',
'Bomba_fog', 
'Bomba_soplante', 
'Calefactores',
'Contador_fog',
'Malla_cenital_Abrir-Desplegar',
'Malla_cenital_Cerrar-Recoger',
'Malla_lateral_Cerrar-Recoger',
'Malla_lateral__Abrir-Desplegar',
'Recirculador',
'Ventana_cenital_Oeste_abrir',
'Ventana_cenital_Oeste_cerrar',
'Ventana_cenital_este_abrir',
'Ventana_cenital_este_cerrar',
'Ventana_lateral_Norte_abrir',
'Ventana_lateral_Norte_cerrar',
'Ventana_lateral_Oeste_abrir',
'Ventana_lateral_Oeste_cerrar',
'Ventana_lateral_Sur_abrir',
'Ventana_lateral_Sur_cerrar',

'Recirculador_centro',
'Recirculador_del_fog',
'Pantalla_de_sombreo_cenital',
'Pantalla_de_sombreo_lateral_sur',
'Ventana_cenital_este',
'Ventana_cenital_oeste',
'Ventana_lateral_norte',
'Ventana_lateral_oeste',
'Ventana_lateral_sur'
]

In [21]:
inside_devices_name = [#'Bomba_fog', 
#'Bomba_soplante', 
'CO2',
'Calefactores',
'Contador_fog',
'HR_Alta',
'HR_Baja',
'HR_Centro',
#'Malla_cenital_Abrir-Desplegar',
#'Malla_cenital_Cerrar-Recoger',
#'Malla_lateral_Cerrar-Recoger',
#'Malla_lateral__Abrir-Desplegar',
'PAR',
'Presión_Barométrica_Alta',
'Presión_Barométrica_Baja',
'Presión_Barométrica_Centro',
'Presión_Vapor_Alta',
'Presión_Vapor_Baja',
'Radiación_Solar_Global',
'Recirculador',
'Temperatura_Alta',
'Temperatura_Baja',
'Temperatura_Centro',
'Velocidad_viento',
#'Ventana_cenital_Oeste_abrir',
#'Ventana_cenital_Oeste_cerrar',
#'Ventana_cenital_este_abrir',
#'Ventana_cenital_este_cerrar',
#'Ventana_lateral_Norte_abrir',
#'Ventana_lateral_Norte_cerrar',
#'Ventana_lateral_Oeste_abrir',
#'Ventana_lateral_Oeste_cerrar',
#'Ventana_lateral_Sur_abrir',
#'Ventana_lateral_Sur_cerrar',
'Fog',
'PAR_interior_(µmol_m_-2_s_-1)',
'Humedad_Relativa_interior_Alta_(%)',
'Humedad_Relativa_interior_Baja_(%)',
'Humedad_Relativa_interior_Centro_(%)',
'DPV_(kPa)',
'CO2_(ppm)',
'Pantalla_de_sombreo_cenital',
'Pantalla_de_sombreo_lateral_sur',
'Presión_Barométrica_Alta_(kPa)',
'Presión_Barométrica_Baja_(kPa)',
'Presión_Barométrica_Centro_(mbar)',
'Presión_Vapor_Alta_(kPA)',
'Presión_Vapor_Baja_(kPa)',
'Radiación_Solar_Global_Interior_(W_m_-2)',
'Recirculador_centro',
'Recirculador_del_fog',
'Temperatura_Interior_Alta_(ºC)',
'Temperatura_Interior_Baja_(ºC)',
'Temperatura_Interior_Centro_(ºC)',
'Velocidad_viento_Interior_(m_s)',
'Ventana_cenital_este',
'Ventana_cenital_oeste',
'Ventana_lateral_norte',
'Ventana_lateral_oeste',
'Ventana_lateral_sur',
'DPV_(kPa)',
'Luz_artificial_centro-este',
'Luz_artificial_centro-oeste',
'Luz_artificial_nor-este',
'Luz_artificial_nor-oeste',
'Luz_artificial_sur-este',
'Luz_artificial_sur-oeste']

In [39]:
# for auguts experiments
inside_devices_name = [
'Recirculador',
'Calefactores',
'Fog',
'PAR_interior_(µmol_m_-2_s_-1)',
'Humedad_Relativa_interior_Alta_(%)',
'Humedad_Relativa_interior_Baja_(%)',
'Humedad_Relativa_interior_Centro_(%)',
'DPV_(kPa)',
'CO2_(ppm)',
'Pantalla_de_sombreo_cenital',
'Pantalla_de_sombreo_lateral_sur',
'Radiación_Solar_Global_Interior_(W_m_-2)',
'Recirculador_centro',
'Recirculador_del_fog',
'Temperatura_Interior_Alta_(ºC)',
'Temperatura_Interior_Baja_(ºC)',
'Temperatura_Interior_Centro_(ºC)',
'Velocidad_viento_Interior_(m_s)',
'Ventana_cenital_este',
'Ventana_cenital_oeste',
'Ventana_lateral_norte',
'Ventana_lateral_oeste',
'Ventana_lateral_sur',
'Luz_artificial_centro-este',
'Luz_artificial_centro-oeste',
'Luz_artificial_nor-este',
'Luz_artificial_nor-oeste',
'Luz_artificial_sur-este',
'Luz_artificial_sur-oeste']

In [40]:
def get_device_data(device_id):
      
  url = "http://localhost:8086/api/v2/query?orgID=3c0e4418759ba99c"

  headers = {"Authorization": "Token kbXDupV8F_mPqj3Loft8A7qx7Hcc9kW2XGUmGjuaNW5tUXgNKBrHIcQ57qxyhlk0y7Rm0FkWgKQfe0anBCPsTg==",
          "Content-Type": "application/vnd.flux"}


  body = '''
  from(bucket: "smart-agriculture")
    |> range(start: 2026-08-03T00:00:00.000Z, stop: 2026-08-26T23:00:00.000Z)
    |> filter(fn: (r) => r["id"] == "{0}")

    |> keep(columns: ["_time", "_value", "device"])
    |> sort(columns: ["_time"])
  '''
#    |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)

  response = requests.post(url, headers=headers, data=body.format(device_id))

  print("Status Code", response.status_code)
  try:
      return pd.read_csv(StringIO(response.text)).drop(columns=['Unnamed: 0','result', 'table', 'device'])
  except EmptyDataError as e:
      print(f"No data for device {device_id}: {e}")
      return pd.DataFrame()


def get_device_ids(device_name, dir):
    url = "http://localhost:8086/api/v2/query?orgID=3c0e4418759ba99c"

    headers = {"Authorization": "Token kbXDupV8F_mPqj3Loft8A7qx7Hcc9kW2XGUmGjuaNW5tUXgNKBrHIcQ57qxyhlk0y7Rm0FkWgKQfe0anBCPsTg==",
            "Content-Type": "application/vnd.flux"}


    body = '''import "influxdata/influxdb/schema"
        schema.tagValues(
        bucket: "smart-agriculture",
        tag: "id",
        predicate: (r) => r.device == "{0}"
        )'''

    response = requests.post(url, headers=headers, data=body.format(device_name))

    print("Status Code", response.status_code)
    print(device_name)
    #print(response.text)
    for i, line in enumerate(response.text.splitlines()[1:]):
        device_id = line.split(',')[-1]
        if device_id != '':
            print(i, device_id)
            df = get_device_data(device_id)
            file_name = f'./{dir}/{device_name}_{i}.csv'
            file_name = file_name.replace('<', 'less').replace('>', 'greater')
            df.to_csv(file_name, index=False)
    print()

In [41]:
for d in inside_devices_name:
    get_device_ids(d, 'climate devices experiments data')

Status Code 200
Recirculador
0 692dd8eb06b4a2ac67a4fd95
Status Code 200
1 692dd8eb06b4a2ac67a4fd96
Status Code 200

Status Code 200
Calefactores
0 692dd8eb06b4a2ac67a4fd8d
Status Code 200
1 692dd8eb06b4a2ac67a4fd8e
Status Code 200
2 69eb455b02f4f4a68c80b31c
Status Code 200

Status Code 200
Fog
0 69e9e8db38bbde2e16b066ea
Status Code 200

Status Code 200
PAR_interior_(µmol_m_-2_s_-1)
0 69eb70ba02f4f4a68c85ec66
Status Code 200

Status Code 200
Humedad_Relativa_interior_Alta_(%)
0 69eb4ac602f4f4a68c8153cf
Status Code 200

Status Code 200
Humedad_Relativa_interior_Baja_(%)
0 69eb707902f4f4a68c85e497
Status Code 200

Status Code 200
Humedad_Relativa_interior_Centro_(%)
0 69eb04e938bbde2e16cb8fca
Status Code 200

Status Code 200
DPV_(kPa)
0 6a03a92602f4f4a68c0dbb47
Status Code 200

Status Code 200
CO2_(ppm)
0 69eb460e02f4f4a68c80c415
Status Code 200

Status Code 200
Pantalla_de_sombreo_cenital
0 69e9d77838bbde2e16aedf12
Status Code 200

Status Code 200
Pantalla_de_sombreo_lateral_sur
0 69e9d73d38bbde2e16aed89b
Status Code 200
No data for device 69e9d73d38bbde2e16aed89b: No columns to parse from file

Status Code 200
Radiación_Solar_Global_Interior_(W_m_-2)
0 69eb75e202f4f4a68c869180
Status Code 200

Status Code 200
Recirculador_centro
0 69e9ea8b38bbde2e16b08817
Status Code 200

Status Code 200
Recirculador_del_fog

Status Code 200
Temperatura_Interior_Alta_(ºC)
0 69eb4a0f02f4f4a68c814127
Status Code 200

Status Code 200
Temperatura_Interior_Baja_(ºC)
0 69eb6ff502f4f4a68c85d2ae
Status Code 200

Status Code 200
Temperatura_Interior_Centro_(ºC)
0 69ea298638bbde2e16b71bba
Status Code 200

Status Code 200
Velocidad_viento_Interior_(m_s)

Status Code 200
Ventana_cenital_este
0 69e9e03e38bbde2e16afa604
Status Code 200

Status Code 200
Ventana_cenital_oeste
0 69e9e08f38bbde2e16afabf6
Status Code 200

Status Code 200
Ventana_lateral_norte
0 69e9dfe538bbde2e16af9fe7
Status Code 200

Status Code 200
Ventana_lateral_oeste
0 69e9df9c38bbde2e16af9895
Status Code 200

Status Code 200
Ventana_lateral_sur
0 69e9df5738bbde2e16af929c
Status Code 200

Status Code 200
Luz_artificial_centro-este
0 69ea28d538bbde2e16b70781
Status Code 200

Status Code 200
Luz_artificial_centro-oeste
0 69ea280438bbde2e16b6efcd
Status Code 200

Status Code 200
Luz_artificial_nor-este
0 69ea28fb38bbde2e16b70c3e
Status Code 200

Status Code 200
Luz_artificial_nor-oeste
0 69ea284e38bbde2e16b6fa2d
Status Code 200

Status Code 200
Luz_artificial_sur-este
0 69ea289838bbde2e16b7019a
Status Code 200

Status Code 200
Luz_artificial_sur-oeste
0 69ea27c338bbde2e16b6e9f7
Status Code 200

# Download outside data

In [ ]:
outside_devices_name = ['Humedad_Relativa_Exterior_(%)',
                'PAR_Exterior_(µmol_m_-2_s_-1)',
                'Precipitación_(mm)',
                'Temperatura_Exterior_(ºC)',
                'Velocidad_viento_Exterior_(m_s)',
                'Temperatura_ambiente',
                'Humedad_ambiente',
                'Precipitación',
                'Precipitación_actual',
                'Velocidad_del_viento',
                'Radiación_solar_par',
                'Radiación_solar_global'
                ]

In [17]:
outside_devices_name = [
                'Temperatura_ambiente',
                'Humedad_ambiente',
                'Precipitación',
                'Precipitación_actual',
                'Velocidad_del_viento',
                'Radiación_solar_par',
                'Radiación_solar_global'
                ]

for d in outside_devices_name:
    get_device_ids(d, 'outside data')

Status Code 200
Temperatura_ambiente
0 68ff33f36eef87228f15c3a5
Status Code 200

Status Code 200
Humedad_ambiente
0 68ff33f36eef87228f15c3ab
Status Code 200

Status Code 200
Precipitación
0 68ff33f36eef87228f15c3c2
Status Code 200

Status Code 200
Precipitación_actual
0 6a1d648402f4f4a68cc9806a
Status Code 200

Status Code 200
Velocidad_del_viento
0 68ff33f36eef87228f15c393
Status Code 200

Status Code 200
Radiación_solar_par
0 68ff33f36eef87228f15c3b1
Status Code 200

Status Code 200
Radiación_solar_global
0 68ff33f36eef87228f15c39f
Status Code 200

# Download forecast data from Open-Meteo

In [23]:
# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://previous-runs-api.open-meteo.com/v1/forecast"
params = {
	"latitude": 38.019826,
	"longitude": -1.167117,
	"hourly": ["temperature_2m", "temperature_2m_previous_day1", "relative_humidity_2m", "relative_humidity_2m_previous_day1", "precipitation", "precipitation_previous_day1", "wind_speed_10m", "wind_speed_10m_previous_day1", "shortwave_radiation", "shortwave_radiation_previous_day1"],
	"models": "ecmwf_ifs",
	"timezone": "auto",
	"wind_speed_unit": "ms",
	"start_date": "2026-01-01",
	"end_date": "2026-07-13",
}
responses = openmeteo.weather_api(url, params = params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation: {response.Elevation()} m asl")
print(f"Timezone: {response.Timezone()}{response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
hourly_temperature_2m_previous_day1 = hourly.Variables(1).ValuesAsNumpy()
hourly_relative_humidity_2m = hourly.Variables(2).ValuesAsNumpy()
hourly_relative_humidity_2m_previous_day1 = hourly.Variables(3).ValuesAsNumpy()
hourly_precipitation = hourly.Variables(4).ValuesAsNumpy()
hourly_precipitation_previous_day1 = hourly.Variables(5).ValuesAsNumpy()
hourly_wind_speed_10m = hourly.Variables(6).ValuesAsNumpy()
hourly_wind_speed_10m_previous_day1 = hourly.Variables(7).ValuesAsNumpy()
hourly_shortwave_radiation = hourly.Variables(8).ValuesAsNumpy()
hourly_shortwave_radiation_previous_day1 = hourly.Variables(9).ValuesAsNumpy()

hourly_data = {
	"date": pd.date_range(
		start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
		end =  pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
		freq = pd.Timedelta(seconds = hourly.Interval()),
		inclusive = "left"
	).tz_convert(response.Timezone().decode())
}

hourly_data["temperature_2m"] = hourly_temperature_2m
hourly_data["temperature_2m_previous_day1"] = hourly_temperature_2m_previous_day1
hourly_data["relative_humidity_2m"] = hourly_relative_humidity_2m
hourly_data["relative_humidity_2m_previous_day1"] = hourly_relative_humidity_2m_previous_day1
hourly_data["precipitation"] = hourly_precipitation
hourly_data["precipitation_previous_day1"] = hourly_precipitation_previous_day1
hourly_data["wind_speed_10m"] = hourly_wind_speed_10m
hourly_data["wind_speed_10m_previous_day1"] = hourly_wind_speed_10m_previous_day1
hourly_data["shortwave_radiation"] = hourly_shortwave_radiation
hourly_data["shortwave_radiation_previous_day1"] = hourly_shortwave_radiation_previous_day1

hourly_dataframe = pd.DataFrame(data = hourly_data)
hourly_dataframe['date'] = hourly_dataframe['date'].apply(lambda x: x.replace(tzinfo=None))
display(hourly_dataframe)

Coordinates: 37.996482849121094°N -1.209686279296875°E
Elevation: 92.0 m asl
Timezone: b'Europe/Madrid'b'GMT+2'
Timezone difference to GMT+0: 7200s

,date,temperature_2m,temperature_2m_previous_day1,relative_humidity_2m,relative_humidity_2m_previous_day1,precipitation,precipitation_previous_day1,wind_speed_10m,wind_speed_10m_previous_day1,shortwave_radiation,shortwave_radiation_previous_day1
0,2025-12-31 23:00:00,7.300000,6.450000,94.988205,92.036911,0.0,0.0,0.141421,0.430116,0.0,0.0
1,2026-01-01 00:00:00,7.050000,6.350000,95.306114,92.351257,0.1,0.0,0.250000,0.650000,0.0,0.0
2,2026-01-01 01:00:00,7.300000,6.500000,95.315277,93.650497,0.0,0.0,0.158114,0.694622,0.0,0.0
3,2026-01-01 02:00:00,6.950000,5.950000,96.957268,95.265503,0.0,0.0,0.509902,0.901388,0.0,0.0
4,2026-01-01 03:00:00,6.750000,5.050000,97.286972,98.960861,0.0,0.0,0.806226,1.101136,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4651,2026-07-13 19:00:00,35.750000,36.450001,36.071602,32.388218,0.0,0.0,3.748333,3.252691,441.0,441.0
4652,2026-07-13 20:00:00,33.599998,35.200001,45.325218,32.357082,0.0,0.0,3.927467,3.460130,277.0,272.0
4653,2026-07-13 21:00:00,31.950001,32.150002,49.584599,39.117195,0.0,0.0,3.332417,3.696282,99.0,102.0
4654,2026-07-13 22:00:00,30.549999,29.900000,53.698837,39.122993,0.0,0.0,2.420744,2.294014,6.0,6.0
4655,2026-07-13 23:00:00,29.400000,28.950001,56.137276,39.112778,0.0,0.0,1.476482,1.140175,0.0,0.0

In [24]:
hourly_dataframe.to_csv('./forecast data/hourly_weather_data.csv', index=False)

In [20]:
hourly_dataframe.describe()

,temperature_2m,temperature_2m_previous_day1,relative_humidity_2m,relative_humidity_2m_previous_day1,precipitation,precipitation_previous_day1,wind_speed_10m,wind_speed_10m_previous_day1,shortwave_radiation,shortwave_radiation_previous_day1
count,4656.000000,4290.000000,4656.000000,4290.000000,4656.000000,4656.000000,4656.000000,4393.000000,4656.000000,4656.000000
mean,17.997196,18.105478,59.848034,60.172062,0.055820,0.045962,2.199689,2.258051,223.204468,224.699951
std,7.817250,8.115127,22.492666,22.816246,0.313417,0.282776,1.685953,1.720155,297.011230,298.954285
min,2.450000,2.350000,7.074285,5.700405,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11.800000,11.650000,42.409019,42.405815,0.000000,0.000000,0.921954,0.965660,0.000000,0.000000
50%,16.700001,16.825001,60.197807,60.559528,0.000000,0.000000,1.668832,1.735656,23.000000,22.000000
75%,23.212501,23.600000,78.830757,79.659866,0.000000,0.000000,3.219084,3.262668,427.000000,431.000000
max,41.900002,42.400002,100.000000,100.000000,6.200000,5.600000,11.574541,11.967038,986.000000,986.000000

# Download rules applied

In [21]:
rules = [
    'Apertura_de_ventanas_cenitales_por_HR_interior_<_70%',
    'Apertura_de_ventanas_cenitales_por_HR_interior_>_70%',
    'Apertura_de_ventanas_cenitales_por_HR_interior_>_72%',
    'Apertura_de_ventanas_laterales_por_HR_interior_>_72%',
    'Apertura_de_ventanas_laterales_por_temperatura_interior',
    'Apertura_de_ventanas_laterales_por_temperatura_interior_>26_am',
    'Apertura_de_ventanas_laterales_por_temperatura_interior_>_28_C',
    'Apertura_de_ventanas_laterales_por_temperatura_interior_>_34_5_C',
    'Apertura_ventanas_Cenitales_>_26_C_am',
    'Apertura_ventanas_Cenitales_por_Alta_temperatura',
    'Apertura_ventanas_Cenitales_por_Alta_temperatura_>_30_C',
    'Apertura_ventanas_Cenitales_por_Alta_temperatura_>_36_C',
    'Apertura_ventanas_Cenitales_por_Alta_temperatura_am',
    'Apertura_ventanas_Cenitales_por_temperatura_>_30_C',
    'Apertura_ventanas_laterales_HR_>_72%',
    'Despliegue_de_Pantalla_Sombreo_Cenital_por_PAR_exterior',
    'Despliegue_de_Pantalla_Sombreo_Cenital_por_PAR_exterior_>_200_µmol_m_-2_s_-1',
    'Despliegue_de_Pantalla_Sombreo_Cenital_por_Temperatura_>35_C',
    'Despliegue_de_Pantalla_Sombreo_Cenital_por_Temperatura_Alta',
    'Despliegue_de_Pantalla_Sombreo_Cenital_por_Temperatura_Alta_>35_C',
    'Despliegue_de_Pantalla_Sombreo_Lateral_Sur',
    'Despliegue_de_Pantalla_Sombreo_Lateral_Sur_300_µmol_m_-2_s_-1',
    'Encender_Luces_PAR_bajo',
    'Encender_Luces_PAR_bajo_<_300_µmol_m_-2_s_-1',
    'Encender_Luces_PAR_bajo_<_50_µmol_m_-2_s_-1_am',
    'Encender_Luces_PAR_bajo_mañana',
    'Encendido_Calefacción_Baja_Temperatura_-_Alta_Humedad_',
    'Encendido_Calefacción_Baja_Temperatura_<_17_C',
    'Fog_para_disminuir_DPV_<_2.1',
    'Fog_para_disminuir_DPV_>_1_7_kPa',
    'Fog_para_subir_HR',
    'Fog_para_subir_HR_<_60%',
    'Recirculador_+_Ventanas_cenitales_para_bajar_humedad_DPV<0_6',
    'Recirculador_por_Temperatura_interior_>_27_C',
    'Recirculador_por_Temperatura_interior_Alta',
    'Recirculador_por_Temperatura_interior_Alta_>_27_C'
]

In [22]:
for d in rules:
    get_device_ids(d, 'inside data/rules')

Status Code 200
Apertura_de_ventanas_cenitales_por_HR_interior_<_70%

Status Code 200
Apertura_de_ventanas_cenitales_por_HR_interior_>_70%
0 6a17085002f4f4a68c99c398
Status Code 200

Status Code 200
Apertura_de_ventanas_cenitales_por_HR_interior_>_72%
0 6a17085002f4f4a68c99c398
Status Code 200

Status Code 200
Apertura_de_ventanas_laterales_por_HR_interior_>_72%
0 6a27b93202f4f4a68cadc5ca
Status Code 200

Status Code 200
Apertura_de_ventanas_laterales_por_temperatura_interior

Status Code 200
Apertura_de_ventanas_laterales_por_temperatura_interior_>26_am
0 6a14093502f4f4a68c07c23b
Status Code 200

Status Code 200
Apertura_de_ventanas_laterales_por_temperatura_interior_>_28_C
0 69ea2dcf38bbde2e16b791d7
Status Code 200

Status Code 200
Apertura_de_ventanas_laterales_por_temperatura_interior_>_34_5_C
0 69ea2dcf38bbde2e16b791d7
Status Code 200

Status Code 200
Apertura_ventanas_Cenitales_>_26_C_am
0 6a1408d702f4f4a68c07a145
Status Code 200

Status Code 200
Apertura_ventanas_Cenitales_por_Alta_temperatura

Status Code 200
Apertura_ventanas_Cenitales_por_Alta_temperatura_>_30_C
0 69f9ca1102f4f4a68c9794cd
Status Code 200

Status Code 200
Apertura_ventanas_Cenitales_por_Alta_temperatura_>_36_C
0 69f9ca1102f4f4a68c9794cd
Status Code 200

Status Code 200
Apertura_ventanas_Cenitales_por_Alta_temperatura_am

Status Code 200
Apertura_ventanas_Cenitales_por_temperatura_>_30_C
0 69f9ca1102f4f4a68c9794cd
Status Code 200

Status Code 200
Apertura_ventanas_laterales_HR_>_72%
0 6a225a9d02f4f4a68ca74dbb
Status Code 200

Status Code 200
Despliegue_de_Pantalla_Sombreo_Cenital_por_PAR_exterior

Status Code 200
Despliegue_de_Pantalla_Sombreo_Cenital_por_PAR_exterior_>_200_µmol_m_-2_s_-1
0 69eb802002f4f4a68c883fff
Status Code 200

Status Code 200
Despliegue_de_Pantalla_Sombreo_Cenital_por_Temperatura_>35_C
0 6a05c18102f4f4a68c61a149
Status Code 200

Status Code 200
Despliegue_de_Pantalla_Sombreo_Cenital_por_Temperatura_Alta

Status Code 200
Despliegue_de_Pantalla_Sombreo_Cenital_por_Temperatura_Alta_>35_C
0 6a05c18102f4f4a68c61a149
Status Code 200

Status Code 200
Despliegue_de_Pantalla_Sombreo_Lateral_Sur

Status Code 200
Despliegue_de_Pantalla_Sombreo_Lateral_Sur_300_µmol_m_-2_s_-1
0 69eb946602f4f4a68c8b82c3
Status Code 200

Status Code 200
Encender_Luces_PAR_bajo

Status Code 200
Encender_Luces_PAR_bajo_<_300_µmol_m_-2_s_-1
0 69eb07c338bbde2e16cbd479
Status Code 200

Status Code 200
Encender_Luces_PAR_bajo_<_50_µmol_m_-2_s_-1_am
0 6a0b14d002f4f4a68c5ca6f2
Status Code 200

Status Code 200
Encender_Luces_PAR_bajo_mañana

Status Code 200
Encendido_Calefacción_Baja_Temperatura_-_Alta_Humedad_

Status Code 200
Encendido_Calefacción_Baja_Temperatura_<_17_C
0 69ec638502f4f4a68ca6d27b
Status Code 200

Status Code 200
Fog_para_disminuir_DPV_<_2.1

Status Code 200
Fog_para_disminuir_DPV_>_1_7_kPa
0 6a185d2902f4f4a68cd9968c
Status Code 200

Status Code 200
Fog_para_subir_HR

Status Code 200
Fog_para_subir_HR_<_60%
0 69eb8e2302f4f4a68c8a6949
Status Code 200

Status Code 200
Recirculador_+_Ventanas_cenitales_para_bajar_humedad_DPV<0_6
0 6a2989cb02f4f4a68c0b7e82
Status Code 200

Status Code 200
Recirculador_por_Temperatura_interior_>_27_C
0 69eb921402f4f4a68c8b2083
Status Code 200

Status Code 200
Recirculador_por_Temperatura_interior_Alta

Status Code 200
Recirculador_por_Temperatura_interior_Alta_>_27_C
0 69eb921402f4f4a68c8b2083
Status Code 200