In [3]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error, root_mean_squared_error
import datetime
from datetime import timedelta

# calculate CVRMSE
def calculate_cvrmse(y_true, y_pred):
    rmse = root_mean_squared_error(y_true, y_pred)
    cvrmse = rmse / y_true.mean()
    return cvrmse

# Inside climatic variables

In [4]:
def readClimaticVariableData(path):
    df = pd.read_csv(path)
    df['_time'] = pd.to_datetime(df['_time'], format='mixed').dt.tz_localize(None).dt.strftime('%Y-%m-%d %H:%M:%S')
    df['_time'] = pd.to_datetime(df['_time'])
    df = df.set_index('_time').resample('h').mean().reset_index()
    return df

df_temperatura_alta = readClimaticVariableData('./inside data/Temperatura_Alta_0.csv')
df_temperatura_baja = readClimaticVariableData('./inside data/Temperatura_Baja_0.csv')
df_temperatura_centro = readClimaticVariableData('./inside data/Temperatura_Centro_0.csv')

df_humedad_alta = readClimaticVariableData('./inside data/HR_Alta_0.csv')
df_humedad_centro = readClimaticVariableData('./inside data/HR_Centro_0.csv')
df_humedad_baja = readClimaticVariableData('./inside data/HR_Baja_0.csv')

df_presion_barometrica_alta = readClimaticVariableData('./inside data/Presión_Barométrica_Alta_0.csv')
df_presion_barometrica_centro = readClimaticVariableData('./inside data/Presión_Barométrica_Centro_0.csv')
df_presion_barometrica_baja = readClimaticVariableData('./inside data/Presión_Barométrica_Baja_0.csv')

df_presion_vapor_alta = readClimaticVariableData('./inside data/Presión_Vapor_Alta_0.csv')
df_presion_vapor_baja = readClimaticVariableData('./inside data/Presión_Vapor_Baja_0.csv')

df_velocidad_viento = readClimaticVariableData('./inside data/Velocidad_Viento_0.csv')

df_par = readClimaticVariableData('./inside data/PAR_0.csv')
df_radiacion_solar = readClimaticVariableData('./inside data/Radiación_Solar_Global_0.csv')

In [92]:
df_temperatura_alta.to_csv('./inside data resampled/temperatura_alta.csv', index=False)
df_temperatura_baja.to_csv('./inside data resampled/temperatura_baja.csv', index=False)
df_temperatura_centro.to_csv('./inside data resampled/temperatura_centro.csv', index=False)

df_humedad_alta.to_csv('./inside data resampled/humedad_alta.csv', index=False)
df_humedad_baja.to_csv('./inside data resampled/humedad_baja.csv', index=False)
df_humedad_centro.to_csv('./inside data resampled/humedad_centro.csv', index=False)

In [5]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=df_temperatura_alta['_time'], y=df_temperatura_alta['_value'], name='Temperatura Alta'))
fig.add_trace(go.Scatter(x=df_temperatura_centro['_time'], y=df_temperatura_centro['_value'], name='Temperatura Centro'))
fig.add_trace(go.Scatter(x=df_temperatura_baja['_time'], y=df_temperatura_baja['_value'], name='Temperatura Baja'))

fig.update_layout(hovermode="x unified")
fig.show()

por qué 3 alturas?

Temperatura alta llega a los picos más altos.

promedio de las 3 temperaturas como target?

In [6]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=df_humedad_alta['_time'], y=df_humedad_alta['_value'], name='Humedad Alta'))
fig.add_trace(go.Scatter(x=df_humedad_centro['_time'], y=df_humedad_centro['_value'], name='Humedad Centro'))
fig.add_trace(go.Scatter(x=df_humedad_baja['_time'], y=df_humedad_baja['_value'], name='Humedad Baja'))

fig.update_layout(hovermode="x unified")
fig.show()

humedad alta llega a los puntos más bajos (más humedo)

In [7]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=df_presion_barometrica_alta['_time'], y=df_presion_barometrica_alta['_value'], name='Presión Barométrica Alta'))
fig.add_trace(go.Scatter(x=df_presion_barometrica_centro['_time'], y=df_presion_barometrica_centro['_value']/10, name='Presión Barométrica Centro'))
fig.add_trace(go.Scatter(x=df_presion_barometrica_baja['_time'], y=df_presion_barometrica_baja['_value'], name='Presión Barométrica Baja'))

fig.update_layout(hovermode="x unified")
fig.show()

la del centro debe dividir entre 10.

In [8]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=df_presion_vapor_alta['_time'], y=df_presion_vapor_alta['_value'], name='Presión de Vapor Alta'))
fig.add_trace(go.Scatter(x=df_presion_vapor_baja['_time'], y=df_presion_vapor_baja['_value'], name='Presión de Vapor Baja'))

fig.update_layout(hovermode="x unified")
fig.show()

In [9]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=df_velocidad_viento['_time'], y=df_velocidad_viento['_value'].clip(lower=0), name='Velocidad de Viento'))
fig.update_layout(hovermode="x unified")
fig.show()


fig = go.Figure()
fig.add_trace(go.Scatter(x=df_par['_time'], y=df_par['_value'].clip(lower=0), name='PAR'))
fig.add_trace(go.Scatter(x=df_radiacion_solar['_time'], y=df_radiacion_solar['_value'].clip(lower=0), name='Radiación Solar'))
fig.update_layout(hovermode="x unified")
fig.show()

valores negativos, par puede tener -0.4?

# Outside climatic variables

## meteo-station

In [10]:
df_precipitacion_exterior = pd.read_csv('./outside data/Precipitación_0.csv')
df_precipitacion_exterior['_time'] = pd.to_datetime(df_precipitacion_exterior['_time'], format='mixed').dt.tz_localize(None).dt.strftime('%Y-%m-%d %H:%M:%S')
df_precipitacion_exterior['_time'] = pd.to_datetime(df_precipitacion_exterior['_time'])
df_precipitacion_exterior['_value'] = df_precipitacion_exterior['_value'].diff()
df_precipitacion_exterior = df_precipitacion_exterior.set_index('_time').resample('h').sum().reset_index()
df_precipitacion_exterior

                   _time  _value
0    2026-01-04 08:00:00     0.7
1    2026-01-04 09:00:00     0.4
2    2026-01-04 10:00:00     0.0
3    2026-01-04 11:00:00     0.0
4    2026-01-04 12:00:00     0.0
...                  ...     ...
3720 2026-06-08 08:00:00     0.0
3721 2026-06-08 09:00:00     0.0
3722 2026-06-08 10:00:00     0.0
3723 2026-06-08 11:00:00     0.0
3724 2026-06-08 12:00:00     0.0

[3725 rows x 2 columns]

In [11]:
df_temperatura_exterior = readClimaticVariableData('./outside data/Temperatura_ambiente_0.csv')
df_humedad_exterior = readClimaticVariableData('./outside data/Humedad_ambiente_0.csv')
df_velocidad_viento_exterior = readClimaticVariableData('./outside data/Velocidad_del_viento_0.csv')
df_par_exterior = readClimaticVariableData('./outside data/Radiación_solar_par_0.csv')

## Forecast data

In [19]:
df_forecast = pd.read_csv('./forecast data/hourly_weather_data.csv')
df_forecast['date'] = pd.to_datetime(df_forecast['date']).apply(lambda x: x - timedelta(hours=2))
df_forecast

,date,temperature_2m,temperature_2m_previous_day1,relative_humidity_2m,relative_humidity_2m_previous_day1,precipitation,precipitation_previous_day1,wind_speed_10m,wind_speed_10m_previous_day1,shortwave_radiation,shortwave_radiation_previous_day1
0,2025-12-31 21:00:00,7.30,6.45,94.988205,92.036910,0.0,0.0,0.141421,0.430116,0.0,0.0
1,2025-12-31 22:00:00,7.05,6.35,95.306114,92.351260,0.1,0.0,0.250000,0.650000,0.0,0.0
2,2025-12-31 23:00:00,7.30,6.50,95.315280,93.650500,0.0,0.0,0.158114,0.694622,0.0,0.0
3,2026-01-01 00:00:00,6.95,5.95,96.957270,95.265500,0.0,0.0,0.509902,0.901388,0.0,0.0
4,2026-01-01 01:00:00,6.75,5.05,97.286970,98.960860,0.0,0.0,0.806226,1.101136,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4651,2026-07-13 17:00:00,35.75,36.45,36.071600,32.388218,0.0,0.0,3.748333,3.252691,441.0,441.0
4652,2026-07-13 18:00:00,33.60,35.20,45.325220,32.357082,0.0,0.0,3.927467,3.460130,277.0,272.0
4653,2026-07-13 19:00:00,31.95,32.15,49.584600,39.117195,0.0,0.0,3.332416,3.696282,99.0,102.0
4654,2026-07-13 20:00:00,30.55,29.90,53.698837,39.122993,0.0,0.0,2.420744,2.294014,6.0,6.0
4655,2026-07-13 21:00:00,29.40,28.95,56.137276,39.112778,0.0,0.0,1.476482,1.140176,0.0,0.0

In [20]:

fig = go.Figure()
for c in df_forecast.columns:
    if c != 'date':
        fig.add_trace(go.Scatter(x=df_forecast['date'], y=df_forecast[c], name=c))


fig.add_trace(go.Scatter(x=df_precipitacion_exterior['_time'], y=df_precipitacion_exterior['_value'].clip(lower=0), name='*Precipitación Exterior'))
fig.add_trace(go.Scatter(x=df_humedad_exterior['_time'], y=df_humedad_exterior['_value'].clip(lower=0), name='*Humedad Exterior'))
fig.add_trace(go.Scatter(x=df_temperatura_exterior['_time'], y=df_temperatura_exterior['_value'].clip(lower=0), name='*Temperatura Exterior'))

fig.add_trace(go.Scatter(x=df_velocidad_viento_exterior['_time'], y=df_velocidad_viento_exterior['_value'].clip(lower=0), name='*Velocidad del Viento Exterior'))
fig.add_trace(go.Scatter(x=df_par_exterior['_time'], y=df_par_exterior['_value'].clip(lower=0), name='*Par Exterior'))

fig.update_layout(hovermode="x unified")
fig.show()

In [23]:
def showMetrics(forecast_df, exterior_df, variable_name):
    # join the two dataframes on the date column
    forecast_df = forecast_df.set_index('date')
    exterior_df = exterior_df.set_index('date')
    joined_df = forecast_df.join(exterior_df.dropna(), how='inner')

    mae = mean_absolute_error(joined_df['_value'], joined_df[variable_name])
    cvrmse = calculate_cvrmse(joined_df['_value'], joined_df[variable_name])
    print(f'{variable_name}: MAE: {mae}, CVRMSE: {cvrmse}')
    return joined_df

# calculate MAE and CVRMSE for each pair variable between forecast and exterior data
joined_temp =showMetrics(df_forecast[['date', 'temperature_2m']], df_temperatura_exterior.rename(columns={'_time': 'date'}), 'temperature_2m')
showMetrics(df_forecast[['date', 'relative_humidity_2m']], df_humedad_exterior.rename(columns={'_time': 'date'}), 'relative_humidity_2m')
showMetrics(df_forecast[['date', 'wind_speed_10m']], df_velocidad_viento_exterior.rename(columns={'_time': 'date'}), 'wind_speed_10m')
showMetrics(df_forecast[['date', 'precipitation']], df_precipitacion_exterior.rename(columns={'_time': 'date'}), 'precipitation')
print()

temperature_2m: MAE: 21.55407149031763, CVRMSE: 4969.975604000243
relative_humidity_2m: MAE: 27.58916030655353, CVRMSE: 33.28603417968638
wind_speed_10m: MAE: 696.5617215114283, CVRMSE: -37.560302084450875
precipitation: MAE: 0.23947368421052634, CVRMSE: -217.13342233420477

# Rules for climatic control systems

In [24]:
df_rule = pd.read_csv('./inside data/rules/Apertura_de_ventanas_cenitales_por_HR_interior_greater_72%_0.csv')
df_rule['_time'] = pd.to_datetime(df_rule['_time'], format='mixed').dt.tz_localize(None).dt.strftime('%Y-%m-%d %H:%M:%S')
df_rule['_time'] = pd.to_datetime(df_rule['_time'])
df_rule

                  _time  _value
0   2026-05-28 04:00:00       1
1   2026-05-28 06:00:10       0
2   2026-05-28 07:50:31       0
3   2026-05-28 07:50:31       0
4   2026-05-28 07:50:32       0
..                  ...     ...
816 2026-07-03 03:00:00       3
817 2026-07-03 04:26:01       4
818 2026-07-03 04:26:04       4
819 2026-07-03 06:01:00       3
820 2026-07-03 06:01:04       3

[821 rows x 2 columns]

In [25]:
datetime.datetime(2026, 5, 31, 5, 43, 39) - datetime.datetime(2026, 5, 31, 5, 12, 4)

datetime.timedelta(seconds=1895)

In [32]:
1895/60

31.583333333333332

In [36]:
calculate_hourly_duration(df_rule, active_value=3).resample('h', on='hour').sum().reset_index()

                   hour  on_minutes
0   2026-05-31 04:00:00   26.566667
1   2026-05-31 05:00:00   31.583333
2   2026-05-31 06:00:00    0.000000
3   2026-05-31 07:00:00    0.000000
4   2026-05-31 08:00:00    0.000000
..                  ...         ...
502 2026-06-21 02:00:00    0.000000
503 2026-06-21 03:00:00   60.000000
504 2026-06-21 04:00:00   60.000000
505 2026-06-21 05:00:00   45.150000
506 2026-06-21 06:00:00    5.883333

[507 rows x 2 columns]

# Climatic control system variables

In [77]:
# read multiple CSV files and combine them into a single DataFrame
def readListCSV(csv_files):
    df = pd.DataFrame()
    for file in csv_files:
        temp_df = pd.read_csv(file)
        temp_df['_time'] = pd.to_datetime(temp_df['_time'], format='mixed', utc=True)
        # remove the timezone information from the _time column
        temp_df['_time'] = temp_df['_time'].dt.tz_localize(None)
        temp_df['_time'] = temp_df['_time'].dt.strftime('%Y-%m-%d %H:%M:%S')
        temp_df['_time'] = pd.to_datetime(temp_df['_time'])
        temp_df['_value'] = temp_df['_value'].clip(lower=0, upper=1)  # Ensure _value is binary (0 or 1)
        df = pd.concat([df, temp_df]).drop_duplicates(subset=['_time']).sort_values(by='_time').reset_index(drop=True)
    return df

# calculate the hourly duration of the active state (ON) 
def calculate_hourly_duration(df, active_value):
    df = df.copy().set_index('_time')
    '''
    if '_time' in df.columns:
        df['_time'] = pd.to_datetime(df['_time'], utc=True, errors='coerce').dt.tz_localize(None)
        df = df.sort_values('_time').set_index('_time')
    else:
        df.index = pd.to_datetime(df.index, utc=True, errors='coerce')
        if getattr(df.index, 'tz', None) is not None:
            df.index = df.index.tz_localize(None)
        df = df.sort_index()
    '''
    # Each row represents the state from its timestamp until the next timestamp.
    intervals = df.reset_index()
    intervals = intervals.rename(columns={intervals.columns[0]: '_time'})
    intervals['next_time'] = intervals['_time'].shift(-1)
    intervals['duration_hours'] = (intervals['next_time'] - intervals['_time']).dt.total_seconds() / 3600

    # Split each ON interval across hourly buckets and sum it.
    rows = []
    for _, row in intervals.dropna(subset=['next_time']).iterrows():
        if row['_value'] == active_value:
            start = row['_time']
            end = row['next_time']
            current = start.floor('h')
            while current < end:
                next_hour = current + pd.Timedelta(hours=1)
                overlap = min(end, next_hour) - max(start, current)
                if overlap.total_seconds() > 0:
                    rows.append((current, overlap.total_seconds() / 60))
                current = next_hour

    hourly_on_minutes = (
        pd.DataFrame(rows, columns=['_time', 'on_minutes'])
        .groupby('_time', as_index=False)['on_minutes']
        .sum()
    )

    return hourly_on_minutes

# read multiple CSV files and combine them into a single DataFrame
def readListCSV_windows_pantalla(csv_files):
    df = pd.DataFrame()
    for file in csv_files:
        temp_df = pd.read_csv(file)
        temp_df['_time'] = pd.to_datetime(temp_df['_time'], format='mixed', utc=True)
        # remove the timezone information from the _time column
        temp_df['_time'] = temp_df['_time'].dt.tz_localize(None)
        temp_df['_time'] = temp_df['_time'].dt.strftime('%Y-%m-%d %H:%M:%S')
        temp_df['_time'] = pd.to_datetime(temp_df['_time'])
        temp_df['_value'] = temp_df['_value'].clip(lower=0)  # Ensure _value is binary (0 or 1)
        df = pd.concat([df, temp_df]).drop_duplicates(subset=['_time']).sort_values(by='_time').reset_index(drop=True)
    return df


# calculate the hourly duration of the active state (ON) 
def calculate_hourly_duration_windows_pantalla(df, active_value):
    df = df.copy().set_index('_time')
    '''
    if '_time' in df.columns:
        df['_time'] = pd.to_datetime(df['_time'], utc=True, errors='coerce').dt.tz_localize(None)
        df = df.sort_values('_time').set_index('_time')
    else:
        df.index = pd.to_datetime(df.index, utc=True, errors='coerce')
        if getattr(df.index, 'tz', None) is not None:
            df.index = df.index.tz_localize(None)
        df = df.sort_index()
    '''
    # Each row represents the state from its timestamp until the next timestamp.
    intervals = df.reset_index()
    intervals = intervals.rename(columns={intervals.columns[0]: '_time'})
    intervals['next_time'] = intervals['_time'].shift(-1)
    intervals['duration_hours'] = (intervals['next_time'] - intervals['_time']).dt.total_seconds() / 3600

    # Split each ON interval across hourly buckets and sum it.
    rows = []
    for _, row in intervals.dropna(subset=['next_time']).iterrows():
        if row['_value'] > active_value:
            start = row['_time']
            end = row['next_time']
            current = start.floor('h')
            while current < end:
                next_hour = current + pd.Timedelta(hours=1)
                overlap = min(end, next_hour) - max(start, current)
                if overlap.total_seconds() > 0:
                    rows.append((current, overlap.total_seconds() / 60))
                current = next_hour

    hourly_on_minutes = (
        pd.DataFrame(rows, columns=['_time', 'on_minutes'])
        .groupby('_time', as_index=False)['on_minutes']
        .sum()
    )

    return hourly_on_minutes

In [27]:
calefactores_files = ['./inside data/calefactores_0.csv', './inside data/calefactores_1.csv', 
             './inside data/calefactores_2.csv']
df_calefactores = readListCSV(calefactores_files)
df_calefactores

                   _time  _value
0    2026-02-25 13:51:33       0
1    2026-02-25 13:57:18       0
2    2026-02-25 13:57:20       0
3    2026-02-25 15:58:20       0
4    2026-02-27 16:30:53       1
...                  ...     ...
2464 2026-07-13 04:27:42       0
2465 2026-07-13 04:27:43       1
2466 2026-07-13 04:27:44       1
2467 2026-07-13 20:00:00       0
2468 2026-07-13 20:00:01       0

[2469 rows x 2 columns]

In [28]:
calculate_hourly_duration(df_calefactores, 1)

                  _time  on_minutes
0   2026-02-27 16:00:00    3.016667
1   2026-03-02 08:00:00    5.833333
2   2026-03-02 09:00:00   25.366667
3   2026-03-02 10:00:00    7.033333
4   2026-03-02 16:00:00   12.333333
..                  ...         ...
769 2026-07-13 15:00:00   60.000000
770 2026-07-13 16:00:00   60.000000
771 2026-07-13 17:00:00   60.000000
772 2026-07-13 18:00:00   60.000000
773 2026-07-13 19:00:00   60.000000

[774 rows x 2 columns]

In [39]:
calefactores_hourly_duration = calculate_hourly_duration(df_calefactores, 1).resample('h', on='_time').sum().reset_index()
calefactores_hourly_duration[calefactores_hourly_duration['_time'] >= '2026-06-11 00:00:00'].to_csv('./inside data resampled/recirculador2_hourly_duration.csv', index=False)
calefactores_hourly_duration = calefactores_hourly_duration[calefactores_hourly_duration['_time'] < '2026-06-11 00:00:00']
calefactores_hourly_duration.to_csv('./inside data resampled/calefactores_hourly_duration.csv', index=False)
calefactores_hourly_duration

                   _time  on_minutes
0    2026-02-27 16:00:00    3.016667
1    2026-02-27 17:00:00    0.000000
2    2026-02-27 18:00:00    0.000000
3    2026-02-27 19:00:00    0.000000
4    2026-02-27 20:00:00    0.000000
...                  ...         ...
2475 2026-06-10 19:00:00    0.000000
2476 2026-06-10 20:00:00    0.000000
2477 2026-06-10 21:00:00    0.000000
2478 2026-06-10 22:00:00    0.000000
2479 2026-06-10 23:00:00    0.000000

[2480 rows x 2 columns]

In [40]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=calefactores_hourly_duration['_time'], y=calefactores_hourly_duration['on_minutes'], name='Calefactores'))
fig.add_trace(go.Scatter(x=df_temperatura_baja['_time'], y=df_temperatura_baja['_value'], name='Temperatura Baja'))
fig.add_trace(go.Scatter(x=df_temperatura_centro['_time'], y=df_temperatura_centro['_value'], name='Temperatura Centro'))
fig.add_trace(go.Scatter(x=df_temperatura_alta['_time'], y=df_temperatura_alta['_value'], name='Temperatura Alta'))
fig.show()

In [32]:
bomba_fog_files = ['./inside data/bomba_fog_0.csv', './inside data/bomba_fog_1.csv']
df_bomba_fog = readListCSV(bomba_fog_files)
df_bomba_fog

                    _time  _value
0     2026-02-25 13:51:33       0
1     2026-02-25 13:57:18       0
2     2026-02-25 13:57:20       0
3     2026-02-25 15:56:07       0
4     2026-02-26 12:34:39       1
...                   ...     ...
43110 2026-07-13 18:25:41       0
43111 2026-07-13 18:29:27       1
43112 2026-07-13 18:29:29       1
43113 2026-07-13 18:29:34       0
43114 2026-07-13 18:29:35       0

[43115 rows x 2 columns]

In [50]:
hourly_bomba_fog = calculate_hourly_duration(df_bomba_fog, 1).resample('h', on='_time').sum().reset_index()
hourly_bomba_fog.to_csv('./inside data resampled/bomba_fog_hourly_duration.csv', index=False)

In [35]:
df_join = pd.merge(hourly_bomba_fog, df_humedad_baja, left_on='_time', right_on='_time', how='inner')
df_join = pd.merge(df_join, df_humedad_centro, left_on='_time', right_on='_time', how='inner')
df_join = pd.merge(df_join, df_humedad_alta, left_on='_time', right_on='_time', how='inner')
df_join.columns = ['_time', 'bomba_fog', 'humedad_baja', 'humedad_centro', 'humedad_alta']
# normalize df_join between 0 and 1 for all columns except _time and on_minutes
#for col in df_join.columns:
#    if col not in ['_time']:
#        df_join[col] = (df_join[col] - df_join[col].min()) / (df_join[col].max() - df_join[col].min())

# visualize all columns in df_join
fig = go.Figure()
for col in df_join.columns:
    if col not in ['_time']:
        fig.add_trace(go.Scatter(x=df_join['_time'], y=df_join[col], name=col))
fig.show()

In [41]:
bomba_soplante_files = ['./inside data/bomba_soplante_0.csv', './inside data/bomba_soplante_1.csv']
df_bomba_soplante = readListCSV(bomba_soplante_files)
df_bomba_soplante

                  _time  _value
0   2026-02-25 13:51:33       0
1   2026-02-25 13:57:18       0
2   2026-02-25 13:57:20       0
3   2026-02-25 15:56:26       0
4   2026-02-26 12:41:29       1
..                  ...     ...
933 2026-07-13 16:00:00       1
934 2026-07-13 16:00:02       1
935 2026-07-13 16:00:05       0
936 2026-07-13 16:00:14       0
937 2026-07-13 16:00:15       0

[938 rows x 2 columns]

In [45]:
calculate_hourly_duration(df_bomba_soplante, 1).resample('h', on='_time').sum().reset_index(
    
).to_csv('./inside data resampled/bomba_soplante_hourly_duration.csv', index=False)

In [48]:
df_fog = readListCSV(['./inside data/Fog_0.csv'])
df_fog

                    _time  _value
0     2026-04-23 09:54:56       0
1     2026-04-23 13:57:28       0
2     2026-04-23 13:57:33       1
3     2026-04-23 13:57:46       0
4     2026-04-23 14:01:13       1
...                   ...     ...
46075 2026-07-13 18:29:35       0
46076 2026-07-13 18:31:04       0
46077 2026-07-13 18:31:05       0
46078 2026-07-13 22:15:34       0
46079 2026-07-13 22:15:36       0

[46080 rows x 2 columns]

In [49]:
calculate_hourly_duration(df_fog, 1).resample('h', on='_time').sum().reset_index(
    
).to_csv('./inside data resampled/fog_hourly_duration.csv', index=False)

In [53]:
df_contador_fog = readListCSV(['./inside data/Contador_Fog_0.csv'])
df_contador_fog

                     _time  _value
0      2026-02-25 13:37:00       0
1      2026-02-25 13:38:00       0
2      2026-02-25 13:51:00       0
3      2026-02-25 13:52:00       0
4      2026-02-25 13:53:00       0
...                    ...     ...
193427 2026-07-13 22:55:00       0
193428 2026-07-13 22:56:00       0
193429 2026-07-13 22:57:00       0
193430 2026-07-13 22:58:00       0
193431 2026-07-13 22:59:00       0

[193432 rows x 2 columns]

In [57]:
df_contador_fog['_value'].unique()

array([0])

In [58]:
recirculador_files = ['./inside data/Recirculador_0.csv', './inside data/Recirculador_1.csv']
df_recirculador = readListCSV(recirculador_files)
df_recirculador

                   _time  _value
0    2026-02-25 13:51:33       0
1    2026-02-25 13:57:18       0
2    2026-02-25 13:57:20       0
3    2026-02-25 15:58:23       0
4    2026-02-26 12:36:14       1
...                  ...     ...
1508 2026-07-13 19:53:26       0
1509 2026-07-13 19:53:28       0
1510 2026-07-13 19:58:29       1
1511 2026-07-13 19:58:30       1
1512 2026-07-13 20:00:00       0

[1513 rows x 2 columns]

In [60]:
calculate_hourly_duration(df_recirculador, 1).resample('h', on='_time').sum().reset_index(
    
).to_csv('./inside data resampled/recirculador_hourly_duration.csv', index=False)

In [ ]:
malla_cenital_Abrir_Desplegar_files = ['./inside data/malla_cenital_Abrir-Desplegar_0.csv', './inside data/malla_cenital_Abrir-Desplegar_1.csv']
df_malla_cenital_Abrir_Desplegar = readListCSV(malla_cenital_Abrir_Desplegar_files)
calculate_hourly_duration(df_malla_cenital_Abrir_Desplegar, 1).resample('h', on='_time').sum().reset_index(
    
).to_csv('./inside data resampled/malla_cenital_Abrir_Desplegar_hourly_duration.csv', index=False)
df_malla_cenital_Abrir_Desplegar

                   _time  _value
0    2026-02-25 13:51:33       0
1    2026-02-25 13:57:18       0
2    2026-02-25 13:57:20       0
3    2026-02-25 15:55:49       0
4    2026-02-25 17:01:02       1
...                  ...     ...
1237 2026-07-13 07:31:06       0
1238 2026-07-13 08:36:02       1
1239 2026-07-13 08:36:05       1
1240 2026-07-13 08:41:02       0
1241 2026-07-13 08:41:03       0

[1242 rows x 2 columns]

## windows/mallas

In [86]:
df_pantalla_sombreo_cenital = readListCSV_windows_pantalla(['./inside data/Pantalla_de_sombreo_cenital_0.csv'])
display(df_pantalla_sombreo_cenital)
calculate_hourly_duration_windows_pantalla(df_pantalla_sombreo_cenital, 0).resample('h', on='_time').sum().reset_index(

).to_csv('./inside data resampled/pantalla_sobreo_cenital.csv', index=False)

                    _time  _value
0     2026-04-23 08:34:33       1
1     2026-04-23 08:34:35       2
2     2026-04-23 08:34:38       3
3     2026-04-23 08:34:41       4
4     2026-04-23 08:34:44       5
...                   ...     ...
58060 2026-07-13 17:38:51       3
58061 2026-07-13 17:38:53       2
58062 2026-07-13 17:38:56       1
58063 2026-07-13 17:38:57       1
58064 2026-07-13 17:38:59       0

[58065 rows x 2 columns]

In [85]:
df_Pantalla_de_sombreo_lateral_sur = readListCSV_windows_pantalla(['./inside data/Pantalla_de_sombreo_lateral_sur_0.csv'])
display(df_Pantalla_de_sombreo_lateral_sur)
calculate_hourly_duration_windows_pantalla(df_Pantalla_de_sombreo_lateral_sur, 0).resample('h', on='_time').sum().reset_index(

).to_csv('./inside data resampled/pantalla_sobreo_lateral_sur.csv', index=False)

                    _time  _value
0     2026-04-23 08:34:34       1
1     2026-04-23 08:34:37       2
2     2026-04-23 08:34:40       3
3     2026-04-23 08:34:43       4
4     2026-04-23 08:34:46       5
...                   ...     ...
43047 2026-07-13 17:05:39       3
43048 2026-07-13 17:05:41       3
43049 2026-07-13 17:05:42       2
43050 2026-07-13 17:05:44       1
43051 2026-07-13 17:05:47       0

[43052 rows x 2 columns]

In [84]:
df_Ventana_cenital_este = readListCSV_windows_pantalla(['./inside data/Ventana_cenital_este_0.csv'])
display(df_Ventana_cenital_este)
calculate_hourly_duration_windows_pantalla(df_Ventana_cenital_este, 0).resample('h', on='_time').sum().reset_index(

).to_csv('./inside data resampled/ventana_cenital_este.csv', index=False)

                    _time  _value
0     2026-04-23 09:23:11       0
1     2026-04-23 09:26:32       0
2     2026-04-23 14:05:30       0
3     2026-04-23 14:05:35       0
4     2026-04-23 14:20:30       0
...                   ...     ...
62290 2026-07-13 08:49:00       0
62291 2026-07-13 08:49:01       0
62292 2026-07-13 08:49:02       0
62293 2026-07-13 19:56:01       0
62294 2026-07-13 19:56:02       0

[62295 rows x 2 columns]

In [87]:
df_Ventana_cenital_oeste = readListCSV_windows_pantalla(['./inside data/Ventana_cenital_oeste_0.csv'])
display(df_Ventana_cenital_oeste)
calculate_hourly_duration_windows_pantalla(df_Ventana_cenital_oeste, 0).resample('h', on='_time').sum().reset_index(

).to_csv('./inside data resampled/ventana_cenital_oeste.csv', index=False)

                    _time  _value
0     2026-04-23 10:34:51       0
1     2026-04-23 10:36:31       0
2     2026-04-23 14:05:30       0
3     2026-04-23 14:05:36       0
4     2026-04-23 14:20:31       0
...                   ...     ...
62781 2026-07-13 08:49:01       0
62782 2026-07-13 08:49:02       0
62783 2026-07-13 08:49:03       0
62784 2026-07-13 19:56:01       0
62785 2026-07-13 19:56:02       0

[62786 rows x 2 columns]

In [88]:
df_Ventana_lateral_norte = readListCSV_windows_pantalla(['./inside data/Ventana_lateral_norte_0.csv'])
display(df_Ventana_lateral_norte)
calculate_hourly_duration_windows_pantalla(df_Ventana_lateral_norte, 0).resample('h', on='_time').sum().reset_index(

).to_csv('./inside data resampled/ventana_lateral_norte.csv', index=False)

                    _time  _value
0     2026-04-23 09:08:55       1
1     2026-04-23 09:08:57       2
2     2026-04-23 09:08:58       3
3     2026-04-23 09:09:02       4
4     2026-04-23 09:09:03       4
...                   ...     ...
50934 2026-07-13 19:01:24       4
50935 2026-07-13 19:01:25       3
50936 2026-07-13 19:01:27       2
50937 2026-07-13 19:01:29       1
50938 2026-07-13 19:01:31       0

[50939 rows x 2 columns]

In [89]:
df_Ventana_lateral_oeste = readListCSV_windows_pantalla(['./inside data/Ventana_lateral_oeste_0.csv'])
display(df_Ventana_lateral_oeste)
calculate_hourly_duration_windows_pantalla(df_Ventana_lateral_oeste, 0).resample('h', on='_time').sum().reset_index(

).to_csv('./inside data resampled/ventana_lateral_oeste.csv', index=False)

                    _time  _value
0     2026-04-23 09:08:53       1
1     2026-04-23 09:08:55       2
2     2026-04-23 09:08:57       3
3     2026-04-23 09:08:59       3
4     2026-04-23 09:09:03       2
...                   ...     ...
46372 2026-07-13 19:02:57       2
46373 2026-07-13 19:02:59       1
46374 2026-07-13 19:03:00       1
46375 2026-07-13 19:03:01       0
46376 2026-07-13 19:03:02       0

[46377 rows x 2 columns]

In [90]:
df_Ventana_lateral_sur = readListCSV_windows_pantalla(['./inside data/Ventana_lateral_sur_0.csv'])
display(df_Ventana_lateral_sur)
calculate_hourly_duration_windows_pantalla(df_Ventana_lateral_sur, 0).resample('h', on='_time').sum().reset_index(

).to_csv('./inside data resampled/ventana_lateral_sur.csv', index=False)

                    _time  _value
0     2026-04-23 14:00:08       1
1     2026-04-23 14:00:09       3
2     2026-04-23 14:00:11       4
3     2026-04-23 14:00:13       5
4     2026-04-23 14:00:14       6
...                   ...     ...
50555 2026-07-13 19:02:57       2
50556 2026-07-13 19:02:59       1
50557 2026-07-13 19:03:00       1
50558 2026-07-13 19:03:01       0
50559 2026-07-13 19:03:02       0

[50560 rows x 2 columns]

In [64]:
malla_cenital_cerrar_recoger_files = ['./inside data/Malla_cenital_Cerrar-Recoger_0.csv', './inside data/Malla_cenital_Cerrar-Recoger_1.csv']
df_malla_cenital_Cerrar_Recoger = readListCSV(malla_cenital_cerrar_recoger_files)
calculate_hourly_duration(df_malla_cenital_Cerrar_Recoger, 1).resample('h', on='_time').sum().reset_index(
    
).to_csv('./inside data resampled/malla_cenital_Cerrar_Recoger_hourly_duration.csv', index=False)
df_malla_cenital_Cerrar_Recoger

                   _time  _value
0    2026-02-25 13:51:33       0
1    2026-02-25 13:57:18       0
2    2026-02-25 13:57:20       0
3    2026-02-25 15:54:23       0
4    2026-02-25 15:55:24       1
...                  ...     ...
1307 2026-07-13 08:11:03       0
1308 2026-07-13 17:33:59       1
1309 2026-07-13 17:34:01       1
1310 2026-07-13 17:38:59       0
1311 2026-07-13 17:39:00       0

[1312 rows x 2 columns]

In [65]:
malla_lateral_abrir_desplegar_files = ['./inside data/Malla_lateral__Abrir-Desplegar_0.csv', './inside data/Malla_lateral__Abrir-Desplegar_1.csv']
df_malla_lateral_Abrir_Desplegar = readListCSV(malla_lateral_abrir_desplegar_files)
calculate_hourly_duration(df_malla_lateral_Abrir_Desplegar, 1).resample('h', on='_time').sum().reset_index(
    
).to_csv('./inside data resampled/malla_lateral_Abrir_Desplegar_hourly_duration.csv', index=False)
df_malla_lateral_Abrir_Desplegar

                   _time  _value
0    2026-02-25 13:51:33       0
1    2026-02-25 13:57:18       0
2    2026-02-25 13:57:20       0
3    2026-02-25 15:55:56       0
4    2026-02-25 17:00:02       1
...                  ...     ...
1261 2026-07-13 09:15:48       0
1262 2026-07-13 09:36:02       1
1263 2026-07-13 09:36:06       1
1264 2026-07-13 09:40:47       0
1265 2026-07-13 09:40:48       0

[1266 rows x 2 columns]

In [67]:
malla_lateral_cerrar_recoger_files = ['./inside data/Malla_lateral_Cerrar-Recoger_0.csv', './inside data/Malla_lateral_Cerrar-Recoger_1.csv']
df_malla_lateral_Cerrar_Recoger = readListCSV(malla_lateral_cerrar_recoger_files)
calculate_hourly_duration(df_malla_lateral_Cerrar_Recoger, 1).resample('h', on='_time').sum().reset_index(
    
).to_csv('./inside data resampled/malla_lateral_Cerrar_Recoger_hourly_duration.csv', index=False)
df_malla_lateral_Cerrar_Recoger

                   _time  _value
0    2026-02-25 13:51:33       0
1    2026-02-25 13:57:18       0
2    2026-02-25 13:57:20       0
3    2026-02-25 15:56:00       0
4    2026-02-25 15:56:55       1
...                  ...     ...
1300 2026-07-13 09:35:47       0
1301 2026-07-13 09:35:48       0
1302 2026-07-13 17:01:02       1
1303 2026-07-13 17:01:06       1
1304 2026-07-13 17:05:47       0

[1305 rows x 2 columns]

In [68]:
ventana_cenital_este_abrir_files = ['./inside data/Ventana_cenital_este_abrir_0.csv', './inside data/Ventana_cenital_este_abrir_1.csv']
df_ventana_cenital_este_abrir = readListCSV(ventana_cenital_este_abrir_files)
calculate_hourly_duration(df_ventana_cenital_este_abrir, 1).resample('h', on='_time').sum().reset_index(
    
).to_csv('./inside data resampled/ventana_cenital_este_abrir_hourly_duration.csv', index=False)
df_ventana_cenital_este_abrir

                   _time  _value
0    2026-01-12 13:02:52       1
1    2026-01-12 13:08:35       0
2    2026-01-16 08:00:10       1
3    2026-01-16 08:03:22       0
4    2026-01-16 08:07:23       1
...                  ...     ...
8220 2026-07-13 06:25:31       0
8221 2026-07-13 06:25:34       1
8222 2026-07-13 06:25:36       0
8223 2026-07-13 06:25:44       1
8224 2026-07-13 06:25:46       0

[8225 rows x 2 columns]

In [70]:
ventana_cenital_este_cerrar_files = ['./inside data/Ventana_cenital_este_cerrar_0.csv', './inside data/Ventana_cenital_este_cerrar_1.csv']
df_ventana_cenital_este_cerrar = readListCSV(ventana_cenital_este_cerrar_files)
calculate_hourly_duration(df_ventana_cenital_este_cerrar, 1).resample('h', on='_time').sum().reset_index(
    
).to_csv('./inside data resampled/ventana_cenital_este_cerrar_hourly_duration.csv', index=False)
df_ventana_cenital_este_cerrar

                   _time  _value
0    2026-01-20 11:56:46       0
1    2026-01-20 12:02:20       0
2    2026-01-20 12:04:02       0
3    2026-01-20 12:06:05       0
4    2026-01-20 12:11:05       0
...                  ...     ...
9661 2026-07-13 08:46:01       1
9662 2026-07-13 08:46:03       0
9663 2026-07-13 08:46:04       1
9664 2026-07-13 08:49:01       0
9665 2026-07-13 08:49:03       0

[9666 rows x 2 columns]